### ISSUE TITLE
authHeaders returns null in UPDATE_HEADER action

### ISSUE THREAD

**Issue by codeeverystory** [yury-dymov/redux-oauth-demo#1]
**action @ 12:11:45.851 AUTH_INIT_SETTINGS**
**prev state** { auth: Map { "signOut": Map { "loading": false, "errors": null }, "authentication": Map { "loading": false, "valid": false, "errors": null }, "oAuthSignIn": Map { "loading": false, "errors": null }, "headers": Map {}, "user": Map { "attributes": null, "isSignedIn": false }, "config": Map {} },
  routing: { locationBeforeTransitions: null },
  reduxAsyncConnect: { loaded: false, loadState: {} } }

{ type: 'AUTH_INIT_SETTINGS',**
/*-----------------------------My initial state inside AUTH_INIT_SETTINGS----------------------------*/
  config:
   { backend:
      { tokenValidationPath: '/auth/validate_token',
        signOutPath: null,
        authProviderPaths: [Object],
        apiUrl: 'http://localhost:3000' },
     tokenFormat:
      { 'access-token': '{{ auth_token }}',
        'token-type': 'Bearer',
        client: '{{ client_id }}',
        expiry: null,
        uid: null,
        authorization: '{{ token-type } { access-token }}' },
     cookieOptions: { key: 'authHeaders', path: '/', expire: 14 },
     cookies:
      { PHPSESSID: 'dbd3js8p026g462b1iir1rb9b0',
        gsScrollPos: '',
        authHeaders: '{}',
        'connect.sid': 's:2tYAdZuIq9-4M9th90QyEo4b2j9XfwLT.2W+HIM/Ub7aXChoFWbmFafegu1dKtHCJvGBChTmy8h0' } } }

**next state**  
{ auth: Map { "signOut": Map { "loading": false, "errors": null }, "authentication": Map { "loading": false, "valid": false, "errors": null }, "oAuthSignIn": Map { "loading": false, "errors": null }, "headers": Map {}, "user": Map { "attributes": null, "isSignedIn": false }, "config": Map { "backend": Map { "tokenValidationPath": "/auth/validate_token", "signOutPath": null, "authProviderPaths": Map { "google": "/auth/google", "outlook": "/auth/outlook" }, "apiUrl": "http://localhost:3000" }, "tokenFormat": Map { "access-token": "{{ auth_token }}", "token-type": "Bearer", "client": "{{ client_id }}", "expiry": null, "uid": null, "authorization": "{{ token-type } { access-token }}" }, "cookieOptions": Map { "key": "authHeaders", "path": "/", "expire": 14 }, "cookies": Map { "PHPSESSID": "dbd3js8p026g462b1iir1rb9b0", "gsScrollPos": "", **"authHeaders": "{}"**, "connect.sid": "s:2tYAdZuIq9-4M9th90QyEo4b2j9XfwLT.2W+HIM/Ub7aXChoFWbmFafegu1dKtHCJvGBChTmy8h0" } } },
  routing: { locationBeforeTransitions: null },
  reduxAsyncConnect: { loaded: false, loadState: {} } }
—— log end ——

**action @ 12:11:45.865 UPDATE_HEADERS**

 **prev state**
{ auth: Map { "signOut": Map { "loading": false, "errors": null }, "authentication": Map { "loading": false, "valid": false, "errors": null }, "oAuthSignIn": Map { "loading": false, "errors": null }, "headers": Map {}, "user": Map { "attributes": null, "isSignedIn": false }, "config": Map { "backend": Map { "tokenValidationPath": "/auth/validate_token", "signOutPath": null, "authProviderPaths": Map { "google": "/auth/google", "outlook": "/auth/outlook" }, "apiUrl": "http://localhost:3000" }, "tokenFormat": Map { "access-token": "{{ auth_token }}", "token-type": "Bearer", "client": "{{ client_id }}", "expiry": null, "uid": null, "authorization": "{{ token-type } { access-token }}" }, "cookieOptions": Map { "key": "authHeaders", "path": "/", "expire": 14 }, "cookies": Map { "PHPSESSID": "dbd3js8p026g462b1iir1rb9b0", "gsScrollPos": "", **"authHeaders": "{}",** "connect.sid": "s:2tYAdZuIq9-4M9th90QyEo4b2j9XfwLT.2W+HIM/Ub7aXChoFWbmFafegu1dKtHCJvGBChTmy8h0" } } },
  routing: { locationBeforeTransitions: null },
  reduxAsyncConnect: { loaded: false, loadState: {} } }

**action**
 action  { type: 'UPDATE_HEADERS', headers: {} }
%c next state color: #4CAF50; font-weight: bold { auth: Map { "signOut": Map { "loading": false, "errors": null }, "authentication": Map { "loading": false, "valid": false, "errors": null }, "oAuthSignIn": Map { "loading": false, "errors": null }, "headers": Map {}, "user": Map { "attributes": null, "isSignedIn": false }, "config": Map { "backend": Map { "tokenValidationPath": "/auth/validate_token", "signOutPath": null, "authProviderPaths": Map { "google": "/auth/google", "outlook": "/auth/outlook" }, "apiUrl": "http://localhost:3000" }, "tokenFormat": Map { "access-token": "{{ auth_token }}", "token-type": "Bearer", "client": "{{ client_id }}", "expiry": null, "uid": null, "authorization": "{{ token-type } { access-token }}" }, "cookieOptions": Map { "key": "authHeaders", "path": "/", "expire": 14 }, "cookies": Map { "PHPSESSID": "dbd3js8p026g462b1iir1rb9b0", "gsScrollPos": "", "authHeaders": "{}", "connect.sid": "s:2tYAdZuIq9-4M9th90QyEo4b2j9XfwLT.2W+HIM/Ub7aXChoFWbmFafegu1dKtHCJvGBChTmy8h0" } } },
  routing: { locationBeforeTransitions: null },
  reduxAsyncConnect: { loaded: false, loadState: {} } }
—— log end ——

**Comment by yury-dymov** [comment]
Hey @codeeverystory, thank you for the report.

It seems that the issue was fixed in the later versions of the redux-oauth. 

I will update this repo in about 15 minutes. Please check if issue is still there

**Comment by yury-dymov** [comment]
Closed due to inactivity. Feel free to reopen in case issue is still there
